version: '3.9'

services:
  app:
    build: .
    container_name: internatura-back
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/feeds?replicaSet=rs0
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DATABASE=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - mongo
      - clickhouse
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - app-network

volumes:
  mongo-data:
  clickhouse_data:

networks:
  app-network:
    driver: bridge